apiVersion: apps/v1
kind: Deployment
metadata: 
  name: typebot-viewer-deployment
  labels: 
    app: typebot-viewer
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: typebot-viewer
  template:     
    metadata: 
      labels: 
        app: typebot-viewer
    spec: 
      containers:
      - name: typebot-viewer
        image: baptistearno/typebot-viewer:latest
        ports:
        - containerPort: 3000
        envFrom: 
          - configMapRef:
              name: typebot-config
          - secretRef: 
              name: typebot-secret
        env:
         - name: DATABASE_URL
           valueFrom:
            secretKeyRef:
              name: postgres-cluster-app
              key: uri              