apiVersion: v1
kind: ConfigMap
metadata:
  name: typebot-config
data: 
  NODE_OPTIONS: "--no-node-snapshot"
  NEXTAUTH_URL: "http://typebot-builder-service" # builder/backend 
  NEXT_PUBLIC_VIEWER_URL: "http://typebot-viewer-service" #viewer/frontend 
  CUSTOM_OAUTH_USER_ID_PATH: "sid"

  CUSTOM_OAUTH_ISSUER: "https://auth.srinohosting.com"
  CUSTOM_OAUTH_NAME: "Zitadel"

  REDIS_URL: "redis://redis-service:6379"