apiVersion: v1
kind: Secret
metadata:
  name: typebot-secret
stringData:  
  ENCRYPTION_SECRET: "1d9RDF1uK3UVPVHSPcdHfXOb/5gFoDDw"

  CUSTOM_OAUTH_CLIENT_ID: "371311828237615129"
  CUSTOM_OAUTH_CLIENT_SECRET: "AfMdCP3z6qXDUdqZ4I2cC2bLClCYYwI3BtIHlOwbdSU5yjtVvuaqvAjLxABXIqdV"
