apiVersion: v1
kind: ConfigMap
metadata:
  name: typebot-config
data: 
  NODE_OPTIONS: "--no-node-snapshot"
  NEXTAUTH_URL: "http://builder.typebot.local:8082" # builder/backend 
  NEXT_PUBLIC_VIEWER_URL: "http://viewer.typebot.local:8082" #viewer/frontend 
  CUSTOM_OAUTH_USER_ID_PATH: "sub"

  CUSTOM_OAUTH_ISSUER: "https://auth.srinohosting.com"
  CUSTOM_OAUTH_NAME: "Zitadel"
  
  REDIS_URL: "redis://redis-service:6379"
  HOSTNAME: "0.0.0.0"