apiVersion: apps/v1
kind: Deployment
metadata:
  name: typebot-builder-deployment # donest connect to anything (for kubectl)
  labels:
    app: typebot-builder
spec:
  replicas: {{ .Values.builder.replicaCount }}
  selector:
    matchLabels:
      app: typebot-builder #
  template:
    metadata:
      labels:
        app: typebot-builder # http://builder.typebot.local:8082/
    spec:
      containers:
        - name: typebot-builder
          image: baptistearno/typebot-builder:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: typebot-config
            - secretRef:
                name: typebot-secret
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-cluster-app
                  key: uri
