apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec: 
      containers:
      - name: redis
        image: redis:alpine
        command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: "/data" # in contianer 
          name: redis-storage # 
      volumes:
      - name: redis-storage # 
        persistentVolumeClaim:
          claimName: redis-pvc # which pvc provides it 